### ISSUE TITLE
Resumo da Aula Inaugal da etapa 00

### ISSUE THREAD

**Issue by EdsonLLima** [edneto/curso-de-js#3]
### Independente se você for:
- coelho(gosta de pular etapa, não fica parado quer inovar e modificar), não pule etapas e evite fazer modificações se no passo a passo ou a aula não sugerir. Na jornada da fluência rápido é ir devagar.
- tartaruga(vai devagar quase parando ou para), não pare siga em frente um passo de cada vez.

Seja tartaruga ou coelho o problema não é quem chega primeiro, mas sim aprender.

----
Empresas que não valorizam as pessoas não valem apena. Não tenha medo de ser julgado, não tenha medo de aplicar as vagas, você não precisa saber de tudo.
Aplique no mínimo para 10 vagas e implemente os feedbacks dos recrutadores, se a empresa não da feedback essa é uma empresa que não vale a pena.

- *Fluência vale mais que apenas construir aplicativos com JavaScript puro, pois você aprende o processo.*

**Comment by edneto** [comment]
Sempre retorno a aula 00 para reforça os passos.
